export const KNOWLEDGE_BASE_ARTICLES = [
  {
    id: 'quick-start-15',
    title: 'Quick Start 15 Minit',
    audience: 'baru',
    level: 'quick-start',
    duration: '15 min',
    tags: ['mula cepat', 'setup', 'operasi harian'],
    summary: 'Setup minimum Rarebits dan jalankan aliran pertama sampai data masuk dashboard.',
    highlights: ['Tetapan asas', 'Tambah item', 'Cipta invois', 'Semak wallet', 'Validasi dashboard'],
    steps: [
      'Tetapkan brand, kategori, dan wallet Business.',
      'Tambah satu item lengkap dengan harga dan media.',
      'Cipta satu invois dan pilih platform jualan sebenar.',
      'Semak transaksi berkaitan dalam wallet.',
      'Pastikan metrik dashboard berubah ikut transaksi.',
    ],
    guidePath: 'docs/learning-center/00-quick-start-15-minit.md',
    theme: 'cyan',
  },
  {
    id: 'asas-aliran',
    title: 'Pengenalan Dan Aliran Kerja',
    audience: 'baru',
    level: 'module',
    duration: '10 min',
    tags: ['asas', 'workflow', 'operational truth'],
    summary: 'Fahami cara Rarebits berfungsi sebagai sistem rekod operasi harian.',
    highlights: ['Konsep operational truth', 'Struktur data', 'Rutin harian/mingguan'],
    steps: [
      'Fahami hubungan item -> invois -> wallet -> dashboard.',
      'Ikut checklist setup hari pertama.',
      'Gunakan rutin harian untuk rekod transaksi konsisten.',
      'Jalankan semakan mingguan dan backup berkala.',
    ],
    guidePath: 'docs/learning-center/01-pengenalan-dan-aliran-kerja.md',
    theme: 'violet',
  },
  {
    id: 'dashboard-operasi',
    title: 'Dashboard Operasi',
    audience: 'semua',
    level: 'module',
    duration: '12 min',
    tags: ['dashboard', 'analitik', 'keputusan'],
    summary: 'Belajar baca metrik utama untuk keputusan stok, pricing, dan aliran tunai.',
    highlights: ['Metrik utama', 'Graf platform/kategori', 'Interpretasi angka'],
    steps: [
      'Semak tempoh tarikh yang tepat sebelum analisis.',
      'Bandingkan revenue dengan net profit.',
      'Pantau trend platform jualan dan caj platform.',
      'Kenal pasti anomali refund/expense untuk audit.',
    ],
    guidePath: 'docs/learning-center/02-dashboard-operasi.md',
    theme: 'rose',
  },
  {
    id: 'inventori-item',
    title: 'Inventori Dan Item',
    audience: 'semua',
    level: 'module',
    duration: '14 min',
    tags: ['inventori', 'item', 'platform iklan'],
    summary: 'Pengurusan data item yang kemas supaya invois dan laporan sentiasa tepat.',
    highlights: ['Field penting item', 'Platform iklan', 'Tag dan media'],
    steps: [
      'Isi nama, kategori, kos, harga, dan kuantiti dengan konsisten.',
      'Tetapkan platform iklan sebagai reminder operasi.',
      'Gunakan platform tempat terjual bila relevan.',
      'Semak status item selepas transaksi selesai.',
    ],
    guidePath: 'docs/learning-center/03-inventori-dan-item.md',
    theme: 'emerald',
  },
  {
    id: 'invois-jualan',
    title: 'Invois Dan Jualan',
    audience: 'semua',
    level: 'module',
    duration: '18 min',
    tags: ['invois', 'jualan', 'platform jualan', 'caj platform'],
    summary: 'Panduan lengkap create/edit invois termasuk shipping mode, fee, cetak, dan share.',
    highlights: ['Create invoice flow', 'Platform invois', 'Fee rule', 'Print/share'],
    steps: [
      'Pilih item/pelanggan dan isi platform jualan invois.',
      'Tetapkan shipping mode ikut transaksi sebenar.',
      'Aktifkan caj platform jika perlu kiraan margin tepat.',
      'Gunakan action cetak A4/thermal/export dan WhatsApp.',
    ],
    guidePath: 'docs/learning-center/04-invois-dan-jualan.md',
    theme: 'sky',
  },
  {
    id: 'pelanggan',
    title: 'Pelanggan',
    audience: 'semua',
    level: 'module',
    duration: '10 min',
    tags: ['pelanggan', 'crm ringan', 'sejarah belian'],
    summary: 'Urus data pelanggan dan semak sejarah transaksi dengan cepat.',
    highlights: ['Senarai pelanggan', 'Detail pelanggan', 'Data quality'],
    steps: [
      'Standardkan nombor telefon dan emel pelanggan.',
      'Semak nilai belian di detail pelanggan.',
      'Gunakan sejarah belian untuk follow-up.',
      'Elak data duplicate dalam akaun sama.',
    ],
    guidePath: 'docs/learning-center/05-pelanggan.md',
    theme: 'amber',
  },
  {
    id: 'wallet-resit',
    title: 'Wallet Dan Resit',
    audience: 'semua',
    level: 'module',
    duration: '16 min',
    tags: ['wallet', 'resit', 'cashflow', 'audit'],
    summary: 'Rekod cashflow masuk/keluar dengan lampiran resit dan muat turun ikut filter.',
    highlights: ['Jenis transaksi', 'Lampiran resit', 'Resit ZIP + manifest'],
    steps: [
      'Rekod sale/expense/topup/transfer/adjustment ikut jenis sebenar.',
      'Lampirkan resit untuk transaksi penting.',
      'Gunakan halaman Senarai Resit untuk preview dan download.',
      'Buat audit mingguan untuk transaksi tanpa resit.',
    ],
    guidePath: 'docs/learning-center/06-wallet-dan-resit.md',
    theme: 'teal',
  },
  {
    id: 'reminder',
    title: 'Reminder',
    audience: 'semua',
    level: 'module',
    duration: '8 min',
    tags: ['reminder', 'calendar', 'follow-up'],
    summary: 'Atur tugas operasi harian dengan reminder list/kalendar dan recurrence.',
    highlights: ['List/calendar mode', 'Recurrence', 'Completion tracking'],
    steps: [
      'Tambah reminder dengan kategori dan priority jelas.',
      'Gunakan recurrence untuk tugas berulang.',
      'Semak due/overdue setiap hari.',
      'Mark complete sebaik selesai.',
    ],
    guidePath: 'docs/learning-center/07-reminder.md',
    theme: 'indigo',
  },
  {
    id: 'katalog-awam',
    title: 'Katalog Awam',
    audience: 'semua',
    level: 'module',
    duration: '9 min',
    tags: ['katalog', 'public page', 'sharing'],
    summary: 'Kumpulkan item dalam katalog awam untuk dikongsi kepada pelanggan.',
    highlights: ['Create/edit katalog', 'Public link', 'Flow katalog -> invois'],
    steps: [
      'Pilih item relevan untuk satu katalog.',
      'Semak cover dan susunan item.',
      'Kongsi pautan public kepada pelanggan.',
      'Tukar item katalog kepada invois bila closing sale.',
    ],
    guidePath: 'docs/learning-center/08-katalog-awam.md',
    theme: 'fuchsia',
  },
  {
    id: 'tetapan-sistem',
    title: 'Tetapan Sistem',
    audience: 'semua',
    level: 'module',
    duration: '14 min',
    tags: ['tetapan', 'brand', 'kategori', 'platform fee'],
    summary: 'Konfigurasi profil, kategori, invoice branding, dan platform fee rules.',
    highlights: ['Profil', 'Kategori', 'Platform fee', 'Brand invois', 'Data safety'],
    steps: [
      'Kemas kini profil dan identiti brand.',
      'Stabilkan senarai kategori untuk konsistensi.',
      'Bina fee rules aktif yang benar-benar digunakan.',
      'Semak tetapan print untuk A4/thermal/paperang.',
    ],
    guidePath: 'docs/learning-center/09-tetapan-sistem.md',
    theme: 'slate',
  },
  {
    id: 'data-safety',
    title: 'Data Safety Backup Restore',
    audience: 'lama',
    level: 'module',
    duration: '20 min',
    tags: ['backup', 'restore', 'disaster', 'idempotency'],
    summary: 'SOP backup dan restore selamat termasuk sandbox test sebelum disaster restore.',
    highlights: ['Full backup', 'Sandbox restore', 'Disaster restore', 'Reconciliation'],
    steps: [
      'Jadualkan backup berkala dan simpan salinan luar.',
      'Uji restore media di sandbox terlebih dahulu.',
      'Semak observability dan reconciliation output.',
      'Guna disaster restore hanya ikut checklist production safe.',
    ],
    guidePath: 'docs/learning-center/10-data-safety-backup-restore.md',
    theme: 'orange',
  },
  {
    id: 'faq-troubleshooting',
    title: 'FAQ Dan Troubleshooting',
    audience: 'semua',
    level: 'module',
    duration: '7 min',
    tags: ['faq', 'debug', 'semakan pantas'],
    summary: 'Rujukan isu lazim seperti platform graf, duplicate pelanggan, dan preview resit.',
    highlights: ['Soalan lazim', 'Checklist debug', 'Audit pantas'],
    steps: [
      'Kenal pasti modul dan rekod ID terlibat.',
      'Semak langkah ulang isu dan mesej ralat.',
      'Bandingkan data source (item vs invoice vs wallet).',
      'Dokumentasikan masa kejadian dan konteks.',
    ],
    guidePath: 'docs/learning-center/11-faq-dan-troubleshooting.md',
    theme: 'pink',
  },
  {
    id: 'advanced-guide',
    title: 'Advanced Guide',
    audience: 'lama',
    level: 'advanced',
    duration: '25 min',
    tags: ['advanced', 'governance', 'audit', 'monthly close'],
    summary: 'Panduan level lanjutan untuk SOP audit, governance data, dan monthly close.',
    highlights: ['Data discipline', 'Margin-aware ops', 'Weekly review', 'Monthly close'],
    steps: [
      'Standardkan naming, platform label, dan rekod exception.',
      'Semak margin bersih ikut platform dan fee behavior.',
      'Jalankan weekly ops review berstruktur.',
      'Lakukan monthly close + backup snapshot akhir bulan.',
    ],
    guidePath: 'docs/learning-center/12-advanced-guide.md',
    theme: 'purple',
  },
];

export const KNOWLEDGE_BASE_AUDIENCES = [
  { id: 'all', label: 'Semua Pengguna' },
  { id: 'baru', label: 'User Baru' },
  { id: 'lama', label: 'User Lama' },
];

export const KNOWLEDGE_BASE_LEVEL_LABEL = {
  'quick-start': 'Quick Start',
  advanced: 'Advanced',
  module: 'Modul',
};
